### PR TITLE
Update actions_list

### PR DESCRIPTION
**Pull request by kait-t**
I TOOK OUT "REASON" FROM INFLUENCE AND ALSO SAID HELLO

NOW I AM CREATING A PULL REQUEST

### CODE REVIEW

**Comment by kait-t** [comment]
AND I AM MERGING WITHOUT REVIEW >:)

**Review by aczaplewski — APPROVED** [review]
HELLO

delete "reason" reason: reduce potential social overlap w Connect looks good.

may want to replace with something to suggest arguing in bad faith e.g. spin

**Comment by aczaplewski** [comment]
I'll leave this open and let u merge it -- unfortunately with review this time >:)

**Comment by kait-t** [comment]
i think i did it!

**Pull request merged**
